#!/usr/bin/env python3

"""
SLIM namelist creator
"""
import sys, os, shutil

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup          import *
from CIME.buildnml                  import create_namelist_infile, parse_input
from CIME.nmlgen                    import NamelistGenerator
from CIME.case                      import Case
from CIME.utils                     import expect, run_cmd

logger = logging.getLogger(__name__)

# pylint: disable=too-many-arguments,too-many-locals,too-many-branches,too-many-statements
####################################################################################
def _create_namelists(case, confdir, inst_string, infile, nmlgen, data_list_path):
####################################################################################
    """Write out the namelist for this component.

    Most arguments are the same as those for `NamelistGenerator`. The
    `inst_string` argument is used as a suffix to distinguish files for
    different instances. The `confdir` argument is used to specify the directory
    in which output files will be placed.
    """
    #------------------------------------------------------
    # Create config dictionary
    #------------------------------------------------------
    config = {}
    config['din_loc_root'] = case.get_value("DIN_LOC_ROOT")
    config['ccsm_co2_ppmv'] = case.get_value("CCSM_CO2_PPMV")
    config['slim_co2_type'] = case.get_value("SLIM_CO2_TYPE")
    config['slim_namelist_opts'] = case.get_value("SLIM_NAMELIST_OPTS")
    config['slim_bldnml_opts'] = case.get_value("SLIM_BLDNML_OPTS")
    config['slim_nml_use_case'] = case.get_value("SLIM_NML_USE_CASE")
    config['slim_force_coldstart'] = case.get_value("SLIM_FORCE_COLDSTART")
    config['comp_glc'] = case.get_value("COMP_GLC")
    config['comp_atm'] = case.get_value("COMP_ATM")
    config['lnd_grid'] = case.get_value("LND_GRID")
    config['lnd_ncpl'] = case.get_value("LND_NCPL")
    config['lnd_domain_path'] = case.get_value("LND_DOMAIN_PATH")
    config['lnd_domain_file'] = case.get_value("LND_DOMAIN_FILE")
    config['ninst_lnd'] = case.get_value("NINST_LND")
    config['rundir'] = case.get_value("RUNDIR")
    config['run_type'] = case.get_value("RUN_TYPE")
    config['run_startdate'] = case.get_value("RUN_STARTDATE")
    config['run_refcase'] = case.get_value("RUN_REFCASE")
    config['run_refdate'] = case.get_value("RUN_REFDATE")
    config['run_reftod'] = case.get_value("RUN_REFTOD")
    config['mask'] = case.get_value("MASK_GRID")

    logger.debug( " SLIM lnd grid is %s", config['lnd_grid'] )

    #------------------------------------------------------
    # Initialize namelist defaults
    #------------------------------------------------------
    nmlgen.init_defaults(infile, config)

    #----------------------------------------------------
    # Write output namelist
    #----------------------------------------------------
    namelist_file = os.path.join(confdir, "lnd_in")
    nmlgen.write_output_file(namelist_file, data_list_path, groups=['slim_inparm'])


###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    """Build the slim namelist """

    # Build the component namelist 
    if compname != "slim":
        raise AttributeError

    lnd_root = case.get_value("COMP_ROOT_DIR_LND")

    # -----------------------------------------------------
    # Clear out old data
    # -----------------------------------------------------

    input_data_list = os.path.join(caseroot,"Buildconf","slim.input_data_list")
    if os.path.exists(input_data_list):
        os.remove(input_data_list)

    # -----------------------------------------------------
    # Set confdir
    # -----------------------------------------------------

    confdir = os.path.join(caseroot, "Buildconf", "slimconf")
    if not os.path.isdir(confdir):
        os.makedirs(confdir)

    # namelist definition file
    namelist_xml_dir = os.path.join(lnd_root, "cime_config")
    definition_file = os.path.join(namelist_xml_dir, "namelist_definition_slim.xml")
    expect(os.path.isfile(definition_file), "Namelist XML file %s not found!" % definition_file)

    # Create the namelist generator object - independent of instance
    nmlgen = NamelistGenerator(case, definition_file)

    #----------------------------------------------------
    # Clear out old data list
    #----------------------------------------------------
    data_list_path = os.path.join(case.get_case_root(), "Buildconf", "slim.input_data_list")
    if os.path.exists(data_list_path):
        os.remove(data_list_path)

    ### Independent of instance...
    startfile_type = "finidat"
    start_type = "default"
    if run_type == "hybrid":
        start_type = "startup"
    elif run_type != "startup":
        start_type = run_type

    if run_type == "branch":
        startfile_type = "nrevsn"
        if slim_force_coldstart == "on":
           slim_force_coldstart = "off"
           logger.warning( "WARNING: You've turned on SLIM_FORCE_COLDSTART for a branch run_type, which is a contradiction, the coldstart will be ignored\n" +
                           "  turn off SLIM_FORCE_COLDSTART, or set RUN_TYPE=hybrid to get rid of this warning"
                         )

    if (slim_force_coldstart == "on"):
        logger.warning( "WARNING: SLIM is starting up from a cold state" )
        start_type = "cold"

    if slim_nml_use_case != "UNSET":
        usecase = "-use_case %s" %slim_nml_use_case
    else:
        usecase = ""

    if ( (mask != "null") and (mask != "UNSET") ):
       gridmask = "-mask %s" %mask
    else:
       gridmask = ""

    start_ymd = run_startdate.replace('-','')

    if ('-01-01' in run_startdate) or ('-09-01' in run_startdate):
        ignore = "-ignore_ic_year"
    else:
        ignore = "-ignore_ic_date"

    infile = os.path.join(confdir, "namelist")
    
    inputdata_file = os.path.join(caseroot,"Buildconf","slim.input_data_list")
    
    lndfrac_file = os.path.join(lnd_domain_path,lnd_domain_file)
    
    # -----------------------------------------------------
    # loop over instances
    # -----------------------------------------------------

    ninst = int(ninst_lnd)
    for inst_counter in range(1, ninst+1):

        # determine instance string
        inst_string = ""
        if ninst > 1:
            inst_string = '_' + '%04d' % inst_counter

        # If multi-instance case does not have restart file, use
        # single-case restart for each instance
        rpointer = "rpointer.lnd" 
        if (os.path.isfile(os.path.join(rundir,rpointer)) and
            (not os.path.isfile(os.path.join(rundir,rpointer + inst_string)))):
            shutil.copy(os.path.join(rundir, rpointer),
                        os.path.join(rundir, rpointer + inst_string))

        ###
        ### instance dependent information...
        ###
        if run_type == "hybrid" or run_type == "branch":
            slim_startfile = "%s.slim%s.r.%s-%s.nc"%(run_refcase,inst_string,run_refdate,run_reftod)
            if not os.path.exists(os.path.join(rundir, slim_startfile)):
                slim_startfile = "%s.slim.r.%s-%s.nc"%(run_refcase,run_refdate,run_reftod)
            slim_icfile = "%s = \'%s\'"%(startfile_type, slim_startfile)
        else:
            slim_icfile = ""
        ###

        infile_lines = []
        infile_lines.append(slim_icfile)

        user_nl_file = os.path.join(caseroot, "user_nl_slim" + inst_string)
        namelist_infile = os.path.join(confdir, "namelist_infile")

        create_namelist_infile(case, user_nl_file, namelist_infile, "\n".join(infile_lines))

        # create namelist
        _create_namelists(case, confdir, inst_string, namelist_infile, nmlgen, data_list_path)
        # -----------------------------------------------------
        # copy resolved namelist to rundir
        # -----------------------------------------------------
        if os.path.isdir(rundir):
            file1 = os.path.join(confdir, "lnd_in")
            file2 = os.path.join(rundir, "lnd_in")
            if ninst > 1:
                file2 += inst_string
            logger.debug("SLIM namelist copy: file1 %s file2 %s " %(file1, file2))
            shutil.copy(file1,file2)

###############################################################################
def _main_func():

    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildnml(case, caseroot, "slim")

if __name__ == "__main__":
    _main_func()
