#!/usr/bin/env python3

"""
SLIM namelist creator executable
"""
import sys, os

_SLIM_PYTHON = os.path.normpath( os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, 'python') )
sys.path.insert(1, _SLIM_PYTHON)

from slim import add_cime_to_path
from slim import add_slim_cime_py_to_path
from slim.slim_logging import setup_logging

from standard_script_setup import *
from CIME.buildnml import parse_input
from CIME.case import Case
from slim_cime_py import buildnml

###############################################################################
def _main_func():

    caseroot = parse_input(sys.argv)
    level = logging.WARNING
    setup_logging( level )
    with Case(caseroot) as case:
        buildnml(case, caseroot, "slim")


if __name__ == "__main__":
    _main_func()
